# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  schoolsystem-api:
    build:
      context: "/Users/vagnerwentz/RiderProjects/SchoolSystem"
      dockerfile: "SchoolSystem.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/SchoolSystem.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "schoolsystem-api:dev"
    ports: []
    volumes:
    - "/Users/vagnerwentz/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/vagnerwentz/RiderProjects/SchoolSystem/SchoolSystem.API:/app:rw"
    - "/Users/vagnerwentz/RiderProjects/SchoolSystem:/src:rw"
    working_dir: "/app"
